#!/bin/sh
mkdir -p /proc /dev /sys
mount -t proc none /proc
mount -t devtmpfs devtmpfs /dev
mount -t sysfs sysfs /sys
cd /samples
setsid cttyhack /bin/sh
echo "Shell exited, shutting down"
poweroff -f
